import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from '@/lib/Providers/providers'
import Navbar from '@/customComponents/Navbar/Navbar'
import { ThemeProvider } from "@/lib/Providers/theme-provider"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en" className='dark'>
      <body>
          <ThemeProvider attribute="class">
            <Navbar />
            {children}
          </ThemeProvider>
      </body>
    </html>
  )
}