name: Build and Push Docker Image to GitLab

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitLab Container Registry
      run: echo "${{ secrets.GITLAB_TOKEN }}" | docker login -u ${{ secrets.GITLAB_USERNAME }} --password-stdin registry.gitlab.com

    - name: Generate timestamp
      id: timestamp
      run: echo "::set-output name=timestamp::$(date +'%d-%m-%Y-%H-%M')"

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .  # The context is your application folder
        file: ./Dockerfile  # Path to your Dockerfile
        push: true  # Push the image to the registry
        tags: registry.gitlab.com/your-username/your-repo:api-${{ steps.timestamp.outputs.timestamp }}  # Image tag